    <map id="_Image-Maps_9201207260941477" name="Image-Maps_9201207260941477">
        <area shape="rect" coords="16,42,148,112" href="#" onclick="submitSearch('sfpf','1');" alt="Parental Resilience" title="Parental Resilience"    />
        <area shape="rect" coords="168,42,300,112" href="#" onclick="submitSearch('sfpf','2');" alt="Social Connections" title="Social Connections"    />
        <area shape="rect" coords="321,42,453,112" href="#" onclick="submitSearch('sfpf','3');" alt="Knowledge of Parent & Child Development" title="Knowledge of Parent & Child Development"    />
        <area shape="rect" coords="475,42,607,112" href="#" onclick="submitSearch('sfpf','4');" alt="Concrete Support in Times of Need" title="Concrete Support in Times of Need"    />
        <area shape="rect" coords="626,42,758,112" href="#" onclick="submitSearch('sfpf','5');" alt="Children's Social & Emotional Development" title="Children's Social & Emotional Development"    />
        <area shape="rect" coords="42,120,119,184" href="#" onclick="submitSearch('domain','12');" alt="Mental Health ~Parent~" title="Mental Health Parent"    />
        <area shape="rect" coords="196,121,273,185" href="#" onclick="submitSearch('domain','6');" alt="Friends, Family, & Community" title="Friends, Family, & Community"    />
        <area shape="rect" coords="347,120,424,184" href="#" onclick="submitSearch('domain','1');" alt="Health & Growth" title="Health & Growth"    />
        <area shape="rect" coords="502,121,579,185" href="#" onclick="submitSearch('domain','9');" alt="Parent Support" title="Parent Support"    />
        <area shape="rect" coords="652,119,732,183" href="#" onclick="submitSearch('domain','6');" alt="Social-Economic Development" title="Social-Economic Development"    />
        <area shape="rect" coords="40,196,120,266" href="#" onclick="submitSearch('domain','11');" alt="Protection from Drug & Alcohol Abuse" title="Protection from Drug & Alcohol Abuse"    />
        <area shape="rect" coords="196,194,277,267" href="#" onclick="submitSearch('domain','10');" alt="Family Relationships" title="Family Relationships"    />
        <area shape="rect" coords="346,194,425,263" href="#" onclick="submitSearch('domain','2');" alt="School Readiness" title="School Readiness"    />
        <area shape="rect" coords="652,194,733,263" href="#" onclick="submitSearch('domain','13');" alt="Mental Health ~Child~" title="Mental Health Child"    />
        <area shape="rect" coords="39,285,120,354" href="#" onclick="submitSearch('domain','8');" alt="Protection from Violence" title="Protection from Violence"    />
        <area shape="rect" coords="342,269,423,338" href="#" onclick="submitSearch('domain','4');" alt="Home Environment" title="Home Environment"    />
        <area shape="rect" coords="651,272,732,341" href="#" onclick="submitSearch('domain','3');" alt="Guidance & Discipline" title="Guidance & Discipline"    />
        <area shape="rect" coords="342,345,423,414" href="#" onclick="submitSearch('domain','5');" alt="Supervision" title="Supervision"    />
        <area shape="rect" coords="651,353,732,422" href="#" onclick="submitSearch('domain','7');" alt="Parenting Styles" title="Parenting Styles"    />
    </map>     
