    <footer class="mainFooter">
		<nav>
			<p align="center">
				<a href="index5_bs.php">Home</a> | <a href="aboutus.php">About Us</a> | <a href="index_map_bs.php">Map Search</a> | <a href="resources.php">Community Resources</a> | <a href="contactus.php">Contact Us</a>
				<span class="contact"></span>Problems with the site? <a href="mailto:ilfarmahan@ualr.edu"> Contact the Webmaster</a>
			</p>
			<p>Copyright &copy; 2016 Arkansas Early Childhood Asset Map</p>
		</nav>
    </footer>